fileName: flm_demo-v3.osm
osm_file_inputPath: input/flm_demo/
osm_file_outputPath: output/flm_demo/

# lanelet2地图坐标系原点的经纬度坐标，lanelet2地图坐标系EUN对齐
origin_lat: 24.9855604238188
origin_lon: 116.88412342557
origin_alt: 333.167083243839





